# required metadata
sonar.projectKey=net.compliancetest:compliencetest
sonar.projectName=ComplienceTest
sonar.projectVersion=1.0

# optional description
sonar.projectDescription=ComplienceTest Project
 
# path to source directories (required)
sonar.sources=.
 

# path to test source directories (optional)
sonar.tests=
 
# path to project binaries (optional), for example directory of Java bytecode
sonar.binaries=
 
# optional comma-separated list of paths to libraries. Only path to JAR file is supported.
sonar.libraries=
 
# The value of the property must be the key of the language.
sonar.language=php
 
# Additional parameters
sonar.phpUnit.skip=true
sonar.phpCodesniffer.skip=true