<div class="popup-box" id="delete-run-box" style="display: none; width: 500px">
    <div class="popup-box-header radius6 noradiusbottom">Delete A Run</div>
    <div class="popup-box-content">
        Deleting a run will delete the associated run profile and all associated transaction log entries. Do you wish to proceed?
    </div>
    <input id="delete-status" type="hidden" value="<?php echo $view->status;?>">
    <input id="delete-prevstatus" type="hidden" value="<?php echo $view->prevstatus;?>">
    <input id="delete-runid" type="hidden" value="<?php echo $view->runid;?>">
    <div class="popup-box-footer radius6 noradiustop">
        <div class="loading loading-with-text radius6"><div><b>DELETING</b><span>Please wait...</span></div></div>
        <a href="#" class="action-btn process-btn"><span class="p"></span><span class="t">Confirm</span></a>
        <a href="#" class="action-btn cancel-btn close-popup-btn"><span class="p"></span><span class="t">Cancel</span></a>
        <div class="clear"></div>
    </div>
    <a class="close_btn"></a>
</div>