<style>
    .ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
    .ui-timepicker-div dl { text-align: left; }
    .ui-timepicker-div dl dt { float: left; clear:left; padding: 0 0 0 5px; }
    .ui-timepicker-div dl dd { margin: 0 10px 10px 40%; }
    .ui-timepicker-div td { font-size: 90%; }
    .ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }
    .ui-timepicker-div .ui_tpicker_unit_hide{ display: none; }

    .ui-timepicker-rtl{ direction: rtl; }
    .ui-timepicker-rtl dl { text-align: right; padding: 0 5px 0 0; }
    .ui-timepicker-rtl dl dt{ float: right; clear: right; }
    .ui-timepicker-rtl dl dd { margin: 0 40% 10px 10px; }

    /* Shortened version style */
    .ui-timepicker-div.ui-timepicker-oneLine { padding-right: 2px; }
    .ui-timepicker-div.ui-timepicker-oneLine .ui_tpicker_time,
    .ui-timepicker-div.ui-timepicker-oneLine dt { display: none; }
    .ui-timepicker-div.ui-timepicker-oneLine .ui_tpicker_time_label { display: block; padding-top: 2px; }
    .ui-timepicker-div.ui-timepicker-oneLine dl { text-align: right; }
    .ui-timepicker-div.ui-timepicker-oneLine dl dd,
    .ui-timepicker-div.ui-timepicker-oneLine dl dd > div { display:inline-block; margin:0; }
    .ui-timepicker-div.ui-timepicker-oneLine dl dd.ui_tpicker_minute:before,
    .ui-timepicker-div.ui-timepicker-oneLine dl dd.ui_tpicker_second:before { content:':'; display:inline-block; }
    .ui-timepicker-div.ui-timepicker-oneLine dl dd.ui_tpicker_millisec:before,
    .ui-timepicker-div.ui-timepicker-oneLine dl dd.ui_tpicker_microsec:before { content:'.'; display:inline-block; }
    .ui-timepicker-div.ui-timepicker-oneLine .ui_tpicker_unit_hide,
    .ui-timepicker-div.ui-timepicker-oneLine .ui_tpicker_unit_hide:before{ display: none; }

    .ui-datepicker .ui-datepicker-buttonpane button{ padding: 0.2em 0.6em 1.6em; }
</style>
<div class="popup-box" style="display: none; width: 450px;" id="trigger_run">
    <div class="popup-box-header radius6 noradiusbottom">Trigger Run</div>
    <div class="popup-box-content grid-box-body">
        <p>Do you wish to trigger this run at the selected time?</p>
        <input type="datetime" name="datetime" id="datetime">
        <div class="validation_error" style="color: red; font-size: smaller; display: none; max-width: 85%;">A run can only be scheduled to start in the future</div>
    </div>
    <div class="popup-box-footer radius6 noradiustop">
        <a class="action-btn process-btn trigger-run" href="#"><span class="p"></span><span class="t">Confirm</span></a>
        <a href="#" class="action-btn cancel-btn close-popup-btn"><span class="p"></span><span class="t">Close</span></a>
        <div class="clear"></div>
    </div>
    <a class="close_btn"></a>
    <div class="loading loading_run"></div>
</div>
<script src="<?php echo '/wp-content/themes/bp-child/js/jquery-ui-timepicker-addon.js';?>" type="text/javascript"></script>
<script type="application/javascript">
    jQuery(document).ready(function(){
        jQuery('#datetime').datetimepicker({
            timeFormat: "H:mm",
            dateFormat: 'yy-mm-dd'
        });
        jQuery('.trigger-run').on('click', function($){
            var time = jQuery('#datetime').val();
            jQuery('.loading_run').show();
            jQuery('#datetime').removeClass('input-error');
            jQuery('.validation_error').hide();
            jQuery.ajax({
                url: '/',
                type: 'post',
                data: {
                    'td-action' : '<?php echo wp_create_nonce('execute-schedule');?>',
                    'profile_id' : '<?php echo $view->id;?>',
                    'datetime' : time
                },
                success: function(response){
                    if (response == 'success') {
                        if (window.location.href.indexOf('my-transaction-log') != -1) {
                            jQuery('.loading_run').hide();
                            setTimeout("jQuery('#trigger-schedule-link').click()", 200);
                            setTimeout("jQuery('#refresh_trigger_data').click()", 300);
                        } else {
                            location.reload();
                        }
                    } else {
                        jQuery('.loading_run').hide();
                        jQuery('#datetime').addClass('input-error');
                        jQuery('.validation_error').show();
                    }
                }
            })
        });
    });
</script>
