<?php
    $esb = new ManageESB();
    $schedules = $esb->getUserSchedules( get_current_user_id() );
?>
<div class="popup-box view-profile-type-box" style="display: none; width: 800px;" id="run_list">
    <div class="popup-box-header radius6 noradiusbottom">Runs list</div>
    <div class="popup-box-content grid-box-body">
        <table id="schedules_table">
            <tr style="font-weight: bold;">
                <td>Product</td>
                <td>Profile</td>
                <td>Start Date/Time</td>
                <td>Status</td>
                <td class="schedules-table-actions">Action</td>
            </tr>
            <?php foreach( $schedules AS $schedule ):?>
                <?php
                    $profile_url = explode('/', $schedule->PROFILE_S3_URL );
                    $profile_token = str_replace( '.json', '', end( $profile_url ) );
                    $profile = ProfileInstance::getProfileBy( 'token', $profile_token );
                    $productID = get_post_id_by_meta_key_and_value('product_id', $schedule->PRODUCT_ID );
                ?>
                <tr>
                    <td><a href="<?php echo get_permalink( $productID );?>"><?php echo get_the_title( $productID );?></a></td>
                    <td><a href="<?php echo S3Wrapper::getProfileLink( $profile->token, $profile->profile_name, true );?>" target="_blank"><?php echo $profile->profile_name;?></a></td>
                    <td>-</td>
                    <td><?php echo $schedule->SCHEDULE_STATUS_LABEL;?></td>
                    <td class="schedules-table-actions">
                        <?php if( $schedule->SCHEDULE_STATUS_CODE == 'PAUSED' ):?>
                            <a href="#" class="change_status action-btn icon-btn terminate-btn has-tooltip" data-status="TERMINATED" data-prevstatus="<?php echo $schedule->SCHEDULE_STATUS_CODE;?>" data-runid="<?php echo $schedule->ID;?>"><span class="p"></span><span class="simple_tooltip radius6">Terminate<span></span></span></a>
                        <?php else: ?>
                            <a href="javascript:void(0);" class="action-btn icon-btn terminate-btn has-tooltip greyed-out-btn"><span class="p"></span><span class="simple_tooltip radius6">Terminate<span></span></span></a>
                        <?php endif;?>

                        <?php
                        //Trigger will only be available to runs in the "Prepared"or "Paused" state.
                        if( in_array( $schedule->SCHEDULE_STATUS_CODE, array( 'PREPARED', 'PAUSED' ) ) ):?>
                                <a href="<?php echo the_permalink() ?>?td-action=<?php echo wp_create_nonce('trigger_run')?>&id=<?php echo $profile->id?>" class="trigger_row action-btn icon-btn play-btn has-tooltip" rel="custom-popup" cp-type="ajax" cp-closeWhenClickOveraly=0 cp-removeBoxAfterClose=1><span class="p"></span><span class="simple_tooltip radius6">Trigger<span></span></span></a>
                        <?php else: ?>
                             <a href="javascript:void(0);" class="action-btn icon-btn play-btn has-tooltip greyed-out-btn"><span class="p"></span><span class="simple_tooltip radius6">Trigger<span></span></span></a>
                        <?php endif;?>

                        <?php
                        //Pause will only be available for runs in the "Executing" state.
                        if( in_array( $schedule->SCHEDULE_STATUS_CODE, array( 'EXECUTING' ) ) ):?>
                            <a href="#" class="change_status action-btn icon-btn pause-btn has-tooltip" data-status="PAUSED" data-prevstatus="EXECUTING" data-runid="<?php echo $schedule->ID;?>"><span class="p"></span><span class="simple_tooltip radius6">Pause<span></span></span></a>
                        <?php else: ?>
                            <a href="javascript:void(0);" class="action-btn icon-btn pause-btn has-tooltip greyed-out-btn"><span class="p"></span><span class="simple_tooltip radius6">Pause<span></span></span></a>
                        <?php endif;?>

                        <?php
                        //Delete will only be available to runs in the "Executed" or "Terminated" state.
                        if( in_array( $schedule->SCHEDULE_STATUS_CODE, array( 'EXECUTED', 'TERMINATED', 'PREPARED' ) ) ):?>
                            <a href="#" class="change_status action-btn icon-btn delete-btn has-tooltip" data-status="DELETED" data-prevstatus="<?php echo $schedule->SCHEDULE_STATUS_CODE;?>" data-runid="<?php echo $schedule->ID;?>"><span class="p"></span><span class="simple_tooltip radius6">Delete<span></span></span></a>
                        <?php else: ?>
                            <a href="javascript:void(0);" class="action-btn icon-btn delete-btn has-tooltip greyed-out-btn"><span class="p"></span><span class="simple_tooltip radius6">Delete<span></span></span></a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
    <div class="popup-box-footer radius6 noradiustop">
        <a href="#" class="action-btn cancel-btn close-popup-btn"><span class="p"></span><span class="t">Close</span></a>
        <div class="clear"></div>
    </div>
    <a class="close_btn"></a>
    <div class="loading loading_schedule"></div>
</div>
<script type="application/javascript">
    jQuery(document).ready(function(){
        jQuery(".trigger_row").off("click").cplightbox();
        jQuery('.change_status').on('click', function(){
            jQuery('.loading_schedule').show();
            jQuery.ajax({
                url: '/',
                type: 'post',
                data: { 'td-action' : '<?php echo wp_create_nonce('change-schedule-status');?>', 'id' : jQuery(this).attr('data-runid'), 'status' : jQuery(this).attr('data-status'), 'prevstatus' : jQuery(this).attr('data-prevstatus') },
                success: function(){
                    jQuery('.close_btn').click();
                }
            });
        });
    });
</script>