<form name="filterForm" id="filterForm" method="get" action="<?php echo get_permalink() ?>">
    <div class="search-results-filter">
        <h4 class="filter-head">Filter By:</h4>

        <div class="search-filters-box">
            <ul class="search-filters-list clearfix">
                <li class="first">
                    <label for="subscription">Subscription: <?php if ($filterSubscription != null) { ?><a href="#" class="clear-filter"
                                                                                                                                          title="Clear Filter">X</a><?php } ?>
                    </label>
                    <select name="subscription" id="subscription" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($tSubscriptions)): ?>
                            <?php foreach ($tSubscriptions as $s) { ?>
                                <option value="<?php echo $s->id ?>"
                                        data-org-id="<?php echo $s->organisation_id ?>" <?php echo $filterSubscription != "" && $s->id == intval($filterSubscription) ? "selected='selected'" : "" ?>><?php echo $s->nickname ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="product">Product: <?php if ($filterProduct != "" && $filterProduct != null) { ?><a href="#" class="clear-filter"
                                                                                                                             title="Clear Filter">X</a><?php } ?></label>
                    <select name="product" id="product" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['product'])): ?>
                            <?php foreach ($filters['product'] as $t) { ?>
                                <option
                                    value="<?php echo !$t->product_id ? 0 : $t->product_id ?>" <?php echo $filterProduct != "" && $t->product_id == intval($filterProduct) ? "selected='selected'" : "" ?>><?php echo get_post_meta($t->product_id, 'product_name', true);?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="suite">Test Suite: <?php if ($filterSuite != "" && $filterSuite != null) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?>
                    </label>
                    <select name="suite" id="suite" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['test_suite_id'])): ?>
                            <?php foreach ($filters['test_suite_id'] as $s) { ?>
                                <option
                                    value="<?php echo !$s->test_suite_id ? 0 : $s->test_suite_id ?>" <?php echo $filterSuite != "" && $s->test_suite_id == intval($filterSuite) ? "selected='selected'" : "" ?>>
                                    <?php echo !$s->test_suite_id ? 'Not assigned' : get_post_meta($s->test_suite_id, 'ts_name', true) ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="case">Test Case: <?php if ($filterCase != "" && $filterCase != null) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?>
                    </label>
                    <select name="case" id="case" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['test_case_id'])): ?>
                            <?php foreach ($filters['test_case_id'] as $c) { ?>
                                <option
                                    value="<?php echo !$c->test_case_id ? 0 : $c->test_case_id ?>" <?php echo $filterCase != "" && $c->test_case_id == intval($filterCase) ? "selected='selected'" : "" ?>>
                                    <?php
                                    echo get_the_title($c->test_case_id);
                                    ?>
                                </option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li class="first">
                    <label for="service">TWAIN Data Group: <?php if ($filterGroup) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="group" id="service" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['data_group'])): ?>
                            <?php foreach ($filters['data_group'] as $s) { ?>
                                <option
                                    value="<?php echo $s->data_group ?>" <?php echo $s->data_group == $filterGroup ? "selected='selected'" : "" ?>><?php echo $s->data_group ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="action">TWAIN Data Type: <?php if ($filterType) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="type" id="action" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['data_type'])): ?>
                            <?php foreach ($filters['data_type'] as $a) { ?>
                                <option
                                    value="<?php echo $a->data_argument_type ?>" <?php echo $a->data_argument_type == $filterType ? "selected='selected'" : "" ?>><?php echo $a->data_argument_type ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="partyid">TWAIN Message: <?php if ($filterMessage) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="message" id="partyid" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if (is_iterable($filters['data_message'])): ?>
                            <?php foreach ($filters['data_message'] as $p) { ?>
                                <option
                                    value="<?php echo $p->messages ?>" <?php echo $p->messages == $filterMessage ? "selected='selected'" : "" ?>><?php echo $p->messages ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </li>
                <li>
                    <label for="date">Date: <?php if ($filterDate) { ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <input type="text" name="date" id="date" class="input datepicker" value="<?php echo !$filterDate ? '' : $filterDate; ?>" style="width: 170px;"/>
                </li>
            </ul>
            <div class="search-filter-actions">
                <a class="action-btn process-btn submit-btn" href="#"><span class="p"></span><span class="t">Confirm</span></a>
                <a href="<?php echo get_permalink(); ?>" class="action-btn clear-btn" id="clear-search-filter-btn"><span class="p"></span><span class="t">Clear</span></a>
            </div>
        </div>
    </div>
</form>