<form name="filterForm" id="filterForm" method="get" action="<?php echo get_permalink()?>">
    <div class="search-results-filter">
        <h4 class="filter-head">Filter By:</h4>
        <div class="search-filters-box">
            <ul class="search-filters-list clearfix">
                <li class="first">
                    <label for="organisation">Organisation: <?php if($filterOrganisation != "all"){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="organisation" id="organisation" autocomplete="off" class="select">
                        <option value="all">- All -</option>
                        <?php if( is_iterable( $tOrganisations ) ):?>
                            <?php foreach($tOrganisations as $o){ ?>
                                <option value="<?php echo $o->id?>" <?php echo $filterOrganisation != "" && $o->id == intval($filterOrganisation) ? "selected='selected'" : "" ?>><?php echo $o->organisation_name ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="product">Product / Service: <?php if($filterProduct != "" && $filterProduct != null){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="product" id="product" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tProducts ) ):?>
                            <?php foreach($tProducts as $t){ ?>
                                <option value="<?php echo !$t->PRODUCT_WP_ID ? 0 : $t->PRODUCT_WP_ID?>" <?php echo $filterProduct != "" && $t->PRODUCT_WP_ID == intval($filterProduct) ? "selected='selected'" : "" ?>><?php echo !$t->PRODUCT_WP_ID ? "Not assigned" : $t->PRODUCT_TITLE ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="suite">Test Suite: <?php if($filterSuite != "" && $filterSuite != null){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="suite" id="suite" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tSuites ) ):?>
                            <?php foreach($tSuites as $s){ ?>
                                <option value="<?php echo !$s->ID ? 0 : $s->ID?>" <?php echo $filterSuite != "" && $s->ID == intval($filterSuite) ? "selected='selected'" : "" ?>>
                                    <?php echo !$s->NAME ? 'Not assigned' : $s->NAME?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="case">Test Case: <?php if($filterCase != "" && $filterCase != null){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="case" id="case" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tCases ) ):?>
                            <?php foreach($tCases as $c){ ?>
                                <option value="<?php echo !$c->ID ? 0 : $c->ID?>" <?php echo $filterCase != "" && $c->ID == intval($filterCase) ? "selected='selected'" : "" ?>>
                                    <?php
                                    if($c->NAME == 'DEFAULT')
                                    {
                                        echo 'Not Assigned';
                                    }else{
                                        echo str_replace("_V", " v", $c->NAME);
                                    }
                                    ?>
                                </option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li class="first">
                    <label for="subscription">Subscription: <?php if($filterSubscription != "all"){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="subscription" id="subscription" autocomplete="off" class="select">
                        <option value="all">- All -</option>
                        <option value="my" <?php echo $filterSubscription != "" && $filterSubscription == 'my' ? "selected='selected'" : "" ?>>- My Subscriptions -</option>
                        <?php if( is_iterable( $tSubscriptions ) ):?>
                            <?php foreach($tSubscriptions as $s){ ?>
                                <?php
                                if ($filterOrganisation != 'all' && $s->organisation_id != $filterOrganisation) {
                                    continue;
                                }
                                ?>
                                <option value="<?php echo $s->id?>" data-org-id="<?php echo $s->organisation_id?>" <?php echo $filterSubscription != "" && $s->id == intval($filterSubscription) ? "selected='selected'" : "" ?>><?php echo $s->nickname ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="service">TWAIN Data Group: <?php if($filterOutcome){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="serv" id="service" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tServices ) ):?>
                            <?php foreach($tServices as $s){ ?>
                                <option value="<?php echo $s?>" <?php echo $s == $filterOutcome ? "selected='selected'" : "" ?>><?php echo $s ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="action">TWAIN Data Type: <?php if($filterAudit){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="action" id="action" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tActions ) ):?>
                            <?php foreach($tActions as $a){ ?>
                                <option value="<?php echo $a?>" <?php echo $a == $filterAudit ? "selected='selected'" : "" ?>><?php echo $a ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li>
                    <label for="partyid">TWAIN Message: <?php if($filterScenario){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <select name="partyid" id="partyid" autocomplete="off" class="select">
                        <option value="">- All -</option>
                        <?php if( is_iterable( $tPartyIDs ) ):?>
                            <?php foreach($tPartyIDs as $p){ ?>
                                <option value="<?php echo $p?>" <?php echo $p == $filterScenario ? "selected='selected'" : "" ?>><?php echo $p ?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
                <li class="first">
                    <label>Date: <?php if($filterDate){ ?><a href="#" class="clear-filter" title="Clear Filter">X</a><?php } ?></label>
                    <input type="text" name="date" id="date" class="input datepicker" value="<?php echo !$filterDate  ?  '' : $filterDate; ?>" style="width: 170px;"/>
                </li>
                <li>
                    <select id="all_subscriptions" autocomplete="off" style="display: none;">
                        <option value="all">- All -</option>
                        <option value="my">- My Subscriptions -</option>
                        <?php if( is_iterable( $tSubscriptions ) ):?>
                            <?php foreach($tSubscriptions as $s){ ?>
                                <option value="<?php echo $s->id?>" data-org-id="<?php echo $s->organisation_id?>"><?php echo stripslashes( $s->nickname )?></option>
                            <?php } ?>
                        <?php endif;?>
                    </select>
                </li>
            </ul>
            <div class="search-filter-actions">
                <a class="action-btn process-btn submit-btn" href="#"><span class="p"></span><span class="t">Confirm</span></a>
                <a href="<?php echo get_permalink(); ?>" class="action-btn clear-btn" id="clear-search-filter-btn"><span class="p"></span><span class="t">Clear</span></a>
            </div>
        </div>
    </div>
</form>