capsArray = [ "CAP_CUSTOMBASE", "CAP_XFERCOUNT", "ICAP_COMPRESSION", "ICAP_PIXELTYPE", "ICAP_UNITS", "ICAP_XFERMECH", "CAP_AUTHOR", "CAP_CAPTION", "CAP_FEEDERENABLED", "CAP_FEEDERLOADED", "CAP_TIMEDATE", "CAP_SUPPORTEDCAPS", "CAP_EXTENDEDCAPS", "CAP_AUTOFEED", "CAP_CLEARPAGE", "CAP_FEEDPAGE", "CAP_REWINDPAGE", "CAP_INDICATORS", "CAP_PAPERDETECTABLE", "CAP_UICONTROLLABLE", "CAP_DEVICEONLINE", "CAP_AUTOSCAN", "CAP_THUMBNAILSENABLED", "CAP_DUPLEX", "CAP_DUPLEXENABLED", "CAP_ENABLEDSUIONLY", "CAP_CUSTOMDSDATA", "CAP_ENDORSER", "CAP_JOBCONTROL", "CAP_ALARMS", "CAP_ALARMVOLUME", "CAP_AUTOMATICCAPTURE", "CAP_TIMEBEFOREFIRSTCAPTURE", "CAP_TIMEBETWEENCAPTURES", "CAP_CLEARBUFFERS", "CAP_MAXBATCHBUFFERS", "CAP_DEVICETIMEDATE", "CAP_POWERSUPPLY", "CAP_CAMERAPREVIEWUI", "CAP_DEVICEEVENT", "CAP_SERIALNUMBER", "CAP_PRINTER", "CAP_PRINTERENABLED", "CAP_PRINTERINDEX", "CAP_PRINTERMODE", "CAP_PRINTERSTRING", "CAP_PRINTERSUFFIX", "CAP_LANGUAGE", "CAP_FEEDERALIGNMENT", "CAP_FEEDERORDER", "CAP_REACQUIREALLOWED", "CAP_BATTERYMINUTES", "CAP_BATTERYPERCENTAGE", "1 CAP_CAMERASIDE", "1 CAP_SEGMENTED", "CAP_CAMERAENABLED", "CAP_CAMERAORDER", "CAP_MICRENABLED", "CAP_FEEDERPREP", "CAP_FEEDERPOCKET", "CAP_AUTOMATICSENSEMEDIUM", "CAP_CUSTOMINTERFACEGUID", "CAP_SUPPORTEDCAPSSEGMENTUNIQUE", "CAP_SUPPORTEDDATS", "CAP_DOUBLEFEEDDETECTION", "CAP_DOUBLEFEEDDETECTIONLENGTH", "CAP_DOUBLEFEEDDETECTIONSENSITIVITY", "CAP_DOUBLEFEEDDETECTIONRESPONSE", "CAP_PAPERHANDLING", "CAP_INDICATORSMODE", "CAP_PRINTERVERTICALOFFSET", "CAP_POWERSAVETIME", "ICAP_AUTOBRIGHT", "ICAP_BRIGHTNESS", "ICAP_CONTRAST", "ICAP_CUSTHALFTONE", "ICAP_EXPOSURETIME", "ICAP_FILTER", "ICAP_FLASHUSED", "ICAP_GAMMA", "ICAP_HALFTONES", "ICAP_HIGHLIGHT", "ICAP_IMAGEFILEFORMAT", "ICAP_LAMPSTATE", "ICAP_LIGHTSOURCE", "ICAP_ORIENTATION", "ICAP_PHYSICALWIDTH", "ICAP_PHYSICALHEIGHT", "ICAP_SHADOW", "ICAP_FRAMES", "ICAP_XNATIVERESOLUTION", "ICAP_YNATIVERESOLUTION", "ICAP_XRESOLUTION", "ICAP_YRESOLUTION", "ICAP_MAXFRAMES", "ICAP_TILES", "ICAP_BITORDER", "ICAP_CCITTKFACTOR", "ICAP_LIGHTPATH", "ICAP_PIXELFLAVOR", "ICAP_PLANARCHUNKY", "ICAP_ROTATION", "ICAP_SUPPORTEDSIZES", "ICAP_THRESHOLD", "ICAP_XSCALING", "ICAP_YSCALING", "ICAP_BITORDERCODES", "ICAP_PIXELFLAVORCODES", "ICAP_JPEGPIXELTYPE", "ICAP_TIMEFILL", "ICAP_BITDEPTH", "ICAP_BITDEPTHREDUCTION", "ICAP_UNDEFINEDIMAGESIZE", "ICAP_IMAGEDATASET", "ICAP_EXTIMAGEINFO", "ICAP_MINUMUMHEIGHT", "ICAP_MINIMUMWIDTH", "ICAP_AUTODISCARDBLANKPAGES", "ICAP_FLIPROTATION", "ICAP_BARCODEDETECTIONENABLED", "ICAP_SUPPORTEDBARCODETYPES", "ICAP_BARCODEMAXSEARCHPRIORITIES", "ICAP_BARCODESEARCHPRIORITIES", "ICAP_BARCODESEARCHMODE", "ICAP_BARCODEMAXRETRIES", "ICAP_BARCODETIMEOUT", "ICAP_ZOOMFACTOR", "ICAP_PATCHCODEDETECTIONENABLED", "ICAP_SUPPORTEDPATCHCODETYPES", "ICAP_PATCHCODEMAXSEARCHPRIORITIES", "ICAP_PATCHCODESEARCHPRIORITIES", "ICAP_PATCHCODESEARCHMODE", "ICAP_PATCHCODEMAXRETRIES", "ICAP_PATCHCODETIMEOUT", "ICAP_FLASHUSED2", "ICAP_IMAGEFILTER", "ICAP_NOISEFILTER", "ICAP_OVERSCAN", "ICAP_AUTOMATICBORDERDETECTION", "ICAP_AUTOMATICDESKEW", "ICAP_AUTOMATICROTATE", "ICAP_JPEGQUALITY", "1 ICAP_FEEDERTYPE", "1 ICAP_ICCPROFILE", "ICAP_AUTOSIZE", "ICAP_AUTOMATICCROPUSESFRAME", "ICAP_AUTOMATICLENGTHDETECTION", "ICAP_AUTOMATICCOLORENABLED", "ICAP_AUTOMATICCOLORNONCOLORPIXELTYPE", "ICAP_COLORMANAGEMENTENABLED", "ICAP_IMAGEMERGE", "ICAP_IMAGEMERGEHEIGHTTHRESHOLD", "ICAP_SUPPORTEDEXTIMAGEINFO", "ICAP_FILMTYPE", "ICAP_MIRROR", "ICAP_JPEGSUBSAMPLING", "ACAP_XFERMECH" ];

valueTypes = {
    0 : 'TWTY_INT8',
    1:'TWTY_INT16',
    2:'TWTY_INT32',
    3:'TWTY_UINT8',
    4:'TWTY_UINT16',
    5:'TWTY_int',
    6:'TWTY_BOOL',
    7:'TWTY_FIX32',
    8:'TWTY_FRAME',
    9:'TWTY_STR32',
    10:'TWTY_STR64',
    11:'TWTY_STR128',
    12:'TWTY_STR255'
};

types = {
    3: 'TWON_ARRAY',
    4: 'TWON_ENUMERATION',
    5: 'TWON_ONEVALUE',
    6: 'TWON_RANGE'
}