DROP TABLE IF EXISTS `PRODUCT_CONFIGURATION`;

CREATE TABLE `PRODUCT_CONFIGURATION` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` varchar(255) DEFAULT NULL,
  `PRODUCT_TITLE` varchar(500) DEFAULT NULL,
  `PRODUCT_WP_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
