CREATE TABLE `wp_organisations` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `organisation_name` varchar(500) DEFAULT NULL,
  `organisation_domain` varchar(255) DEFAULT NULL,
  `invoice_me` tinyint(2) DEFAULT '1',
  `contact_first_name` varchar(100) DEFAULT NULL,
  `contact_last_name` varchar(100) DEFAULT NULL,
  `contact_email` varchar(500) DEFAULT NULL,
  `abn` varchar(100) DEFAULT NULL,
  `billing_address_attention` varchar(255) DEFAULT NULL,
  `billing_address1` varchar(500) DEFAULT NULL,
  `billing_address2` varchar(500) DEFAULT NULL,
  `billing_address3` varchar(500) DEFAULT NULL,
  `billing_address4` varchar(500) DEFAULT NULL,
  `billing_city` varchar(255) DEFAULT NULL,
  `billing_postcode` varchar(20) DEFAULT NULL,
  `billing_state` varchar(255) DEFAULT NULL,
  `billing_country` varchar(255) DEFAULT NULL,
  `phonenumber` varchar(100) DEFAULT NULL,
  `phonenumber_areacode` varchar(20) DEFAULT NULL,
  `phonenumber_countrycode` varchar(10) DEFAULT NULL,
  `contact_id` varchar(100) DEFAULT NULL,
  `admin_id` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
